/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').options} */
const config = {
  printWidth: 120,
  tabWidth: 2,
  useTabs: false,
  singleQuote: true,
  embeddedSingleQuote: true,
  semi: true,
  trailingComma: 'es5',
  arrowParens: 'avoid',
  bracketSpacing: true,
  htmlWhitespaceSensitivity: 'css',
  singleLineLinkTags: false,
  indentSchema: false,
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss', 'prettier-plugin-rational-order'],
  importOrder: [
    '<THIRD_PARTY_MODULES>',
    '^@/(.*)$',
    '^@/server/(.*)$',
    '^@/utils/(.*)$',
    '^@/blocks/(.*)$',
    '^@/components/components/(.*)$',
    '^@/components/interface/(.*)$',
    '^@/components/layout/(.*)$',
    '^@/styles/(.*)$',
    '^@/style/(.*)$',
    '^./(.*)$.css',
    '^@/types/(.*)$',
    '^../(.*)$',
    '^./(.*)$',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};

export default config;
